# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='product.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rproduct.proto\"o\n\nrequestMsg\x12\r\n\x05RFQID\x18\x01 \x02(\t\x12\x10\n\x08\x63\x63ountID\x18\x02 \x02(\t\x12\x15\n\rproductNumber\x18\x03 \x02(\x05\x12\x17\n\x0fproductCategory\x18\x04 \x02(\t\x12\x10\n\x08Quantity\x18\x05 \x02(\x05\"7\n\x08replyMsg\x12\x11\n\tunitPrice\x18\x01 \x03(\t\x12\x18\n\x10validationPeriod\x18\x02 \x03(\t')
)




_REQUESTMSG = _descriptor.Descriptor(
  name='requestMsg',
  full_name='requestMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RFQID', full_name='requestMsg.RFQID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ccountID', full_name='requestMsg.ccountID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productNumber', full_name='requestMsg.productNumber', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productCategory', full_name='requestMsg.productCategory', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Quantity', full_name='requestMsg.Quantity', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=128,
)


_REPLYMSG = _descriptor.Descriptor(
  name='replyMsg',
  full_name='replyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unitPrice', full_name='replyMsg.unitPrice', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='validationPeriod', full_name='replyMsg.validationPeriod', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['requestMsg'] = _REQUESTMSG
DESCRIPTOR.message_types_by_name['replyMsg'] = _REPLYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

requestMsg = _reflection.GeneratedProtocolMessageType('requestMsg', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMSG,
  __module__ = 'product_pb2'
  # @@protoc_insertion_point(class_scope:requestMsg)
  ))
_sym_db.RegisterMessage(requestMsg)

replyMsg = _reflection.GeneratedProtocolMessageType('replyMsg', (_message.Message,), dict(
  DESCRIPTOR = _REPLYMSG,
  __module__ = 'product_pb2'
  # @@protoc_insertion_point(class_scope:replyMsg)
  ))
_sym_db.RegisterMessage(replyMsg)


# @@protoc_insertion_point(module_scope)
